shop_project/accounts/urls.py
from django.urls import path
from .views import *


app_name = 'accounts'
urlpatterns = [
    path('registration/', registration_view, name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

shop_project/api/urls.py
from django.urls import path
from .views import product_view, categories_view, feedback_view, feedbackupdate_view


urlpatterns = [
	path('', product_view),
	path('categories/', categories_view),
	path('feedback/', feedback_view),
	path('feedback/<int:pk>/', feedbackupdate_view),
]

shop_project/main_app/urls.py
from django.urls import path
from .views import *


app_name = 'main_app'
urlpatterns = [
    path('', MainWithCategory.as_view(), name='supermain'),
    path('product_detail/<int:product_id>/', ProductDetailView.as_view(), name='productdetail'),
    path('<int:category_id>/', MainWithCategory2.as_view(), name='supermain1'),
    path('update_product/<int:product_id>', UpdateProductView.as_view(), name='update_product'),
    path('delete_product/<int:pk>', DeleteProductView.as_view(), name='delete_product'),
    path('form_create_product/', CreateProductView.as_view(), name='product_form'),
    path('main/', main_view, name='main'),
    path('view/', ClassView.as_view(), name='view'),
    path('templateview/', TemplateClassView.as_view(), name='templateview'),
    path('listview/', ClassListView.as_view(), name='listview'),
    path('detailview/<int:pk>/', MyDetailView.as_view(), name='detailview'),
    path('create_product/', create_product_view, name='create_product'),
]

shop_project/shop_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)


urlpatterns = [
    path('', include('main_app.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_project/main_app/models.py
from django.db import models


class Category(models.Model):
    category_name = models.CharField(max_length=150, verbose_name='Категория', unique=True)
    category_slug = models.SlugField(max_length=100, verbose_name='Слаг категории')

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['category_name']


class CountryOfOrigin(models.Model):
    countryoforigin_name = models.CharField(max_length=100, verbose_name='Страна происхождения', unique=True)
    countryoforigin_slug = models.SlugField(max_length=100, verbose_name='Слаг страны происхождения')

    def __str__(self):
        return self.countryoforigin_name

    class Meta:
        verbose_name = 'Страна происхождения'
        verbose_name_plural = 'Страны происхождения'
        ordering = ['countryoforigin_name']


class UnitOfMeasure(models.Model):
    unit_name = models.CharField(max_length=50, verbose_name='Единица измерения', unique=True)

    def __str__(self):
        return self.unit_name

    def new_str(self):
        return 'Ho-ho-ho!'

    class Meta:
        verbose_name = 'Единица измерения'
        verbose_name_plural = 'Единицы измерения'


class Product(models.Model):
    product_name = models.CharField(max_length=200, verbose_name='Наименование товара', unique=True)
    product_slug = models.SlugField(max_length=200, verbose_name='Слаг товара')
    product_price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена товара', blank=True,
                                        null=True)
    product_quantity = models.PositiveIntegerField(verbose_name='Количество товара на складе', blank=True, null=True)
    product_units = models.ForeignKey('UnitOfMeasure', on_delete=models.CASCADE, verbose_name='Единицы измерения',
                                      blank=True, null=True)
    product_image = models.ImageField(verbose_name='Фото товара', upload_to='images/%Y/%m/%d', blank=True, null=True)
    is_available = models.BooleanField(default=True, verbose_name='Доступность', blank=True, null=True)
    product_countriesoforigin = models.ForeignKey('CountryOfOrigin', on_delete=models.CASCADE,
                                                  verbose_name='Страны происхождения', blank=True, null=True)
    product_categories = models.ManyToManyField('Category', verbose_name='Категории', blank=True)
    product_description = models.TextField(verbose_name="Описание товара", blank=True, null=True)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['product_name']

    def __str__(self):
        return f'{self.product_name} ({self.product_countriesoforigin})'

    def get_product_categories(self):
        if self.product_categories.all().exists():
            return ', '.join([c.category_name for c in self.product_categories.all()])
        else:
            return 'У этого товара нет категории'


class FeedbackModel(models.Model):
    product_name = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name="Наименование продукта")
    title = models.CharField(max_length=150, verbose_name="Заголовок")
    content = models.TextField(verbose_name='Содержание')

shop_project/main_app/forms.py
from django import forms
from .models import *


class FilterForm(forms.Form):
    category_name = forms.ModelChoiceField(queryset=Category.objects.all(), label='Категория товара',  required=False, widget=forms.Select())
    product_name = forms.CharField(label='Наименование товара', required=False)
    gl = forms.CharField(widget=forms.Select(choices=[('greater', '>'), ('less', '<')]),
                         label='', required=False)
    product_price = forms.DecimalField(label='Цена товара', required=False)


class CreateProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'product_categories', 'product_countriesoforigin', 'product_quantity',
                  'product_units', 'product_price', 'product_description', 'product_image', 'is_available']
        widgets = {'product_name': forms.TextInput(attrs={'id': 'product_input', 'placeholder': 'Введите название товара'})}

shop_project/main_app/views.py
from decimal import Decimal

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import View, TemplateView
from .custom_mixin import GetContextDataMixin

from .models import *
from .forms import *
from slugify import slugify


def main_view(request):
    products = Product.objects.all()
    form = FilterForm()
    if 'product_name' in request.GET:
        complex_request = []
        if request.GET.get('product_name'):
            complex_request.append(Q(product_name=request.GET['product_name']))
            products = products.filter(product_name=(request.GET['product_name']))
        if request.GET.get('product_price'):
            try:
                price = Decimal(request.GET['product_price'])
                if price >= 0:
                    if request.GET['gl'] == 'greater':
                        complex_request.append(Q(product_price__gt=price))
                        products = products.filter(product_price__gt=price)
                    else:
                        complex_request.append(Q(product_price__lt=price))
                        products = products.filter(product_price__gt=price)
                else:
                    return render(request, template_name='main.html', context={'products': products, 'form': form,
                                                                               'message': 'Цена должна быть числом выше 0'})
            except ValueError:
                return render(request, template_name='main.html', context={'products': products, 'form': form,
                                                                           'message': 'Укажите цену в числовом формате'})
        if request.GET.get('category_name'):
            category_name_id = int(request.GET['category_name'])
            complex_request.append(Q(product_categories=category_name_id))
            products = products.filter(product_categories=category_name_id)
        print(complex_request)
    return render(request, template_name='main.html', context={'products': products, 'form': form})


@login_required
def create_product_view(request):
    if request.method == 'POST':
        form = CreateProductForm(request.POST)
        if form.is_valid():
            form.cleaned_data['product_slug'] = slugify(form.cleaned_data['product_name'])
            form.save()
            return redirect('main')
    else:
        form = CreateProductForm()
        return render(request, template_name='create_product.html', context={'form': form})


class ClassView(View):
    def get(self, request):
        products = Product.objects.all()
        return render(request, template_name='view.html', context={'message': 'Hello', 'products': products})

    def post(self, request):
        return redirect('main_app:main')


class TemplateClassView(TemplateView):
    template_name = 'templateview.html'
    extra_context = {'message': 'Hello again!'}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # print(context)
        context['key'] = 'New page'
        # print(self.kwargs)
        # print(context)
        # print(self.request.__dict__)
        return context


class ClassListView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'listview.html'


class MyDetailView(GetContextDataMixin, DetailView):
    model = Product
    template_name = 'detailview.html'
    # pk_url_kwarg - переопределит название URL параметра в urls.py


class MainWithCategory(GetContextDataMixin, ListView):
    model = Product
    template_name = 'supermain1.html'
    # paginate_by = 4


class MainWithCategory2(GetContextDataMixin, ListView):
    model = Product
    template_name = 'supermain1.html'
    # paginate_by = 3

    def get_queryset(self):
        # print(' self.kwargs: ',  self.kwargs)
        category_id = self.kwargs['category_id']
        qs = super().get_queryset()
        # print('get_queryset returns: ', qs)
        category = get_object_or_404(Category, pk=category_id)
        products = qs.filter(product_categories=category)
        return products


class ProductDetailView(GetContextDataMixin, DetailView):
    model = Product
    template_name = 'product_detail.html'
    context_object_name = 'product'
    pk_url_kwarg = 'product_id'


class CreateProductView(LoginRequiredMixin, GetContextDataMixin, CreateView):
    form_class = CreateProductForm
    template_name = 'form_create_product.html'
    success_url = reverse_lazy('main_app:supermain')


class UpdateProductView(LoginRequiredMixin, GetContextDataMixin, UpdateView):
    form_class = CreateProductForm
    template_name = 'update_product.html'
    success_url = reverse_lazy('main_app:supermain')
    model = Product
    pk_url_kwarg = 'product_id'


class DeleteProductView(GetContextDataMixin, DeleteView):
    model = Product
    template_name = 'delete_product.html'
    success_url = reverse_lazy('main_app:supermain')

shop_project/main_app/templates/create_product.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Store</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table">
        {% for field in form %}
            <tr class="product_tr">
                <td class="product_td">
                    {{ field.label }}
                </td>
                <td class="product_td">
                    {{ field }}
                </td>
            </tr>

        {% endfor %}
            <tr class="product_tr">
                <td class="product_td">
                </td>
                <td class="product_td">
                    <input type="submit" value="Создать">
                </td>
            </tr>
        </table>
    </form>

</body>

shop_project/main_app/templates/delete_product.html
{% extends 'supermain1.html' %}

{% load static %}

{% block content %}
<h2>Удаление продукта</h2>
<form action="" method="POST" style="margin: auto;">
	{% csrf_token %}
	<table>
		<tr>
			<td>
				{{ product.product_name }}
			</td>
			<td>
			
			</td>
		</tr>
		
		<tr>
			<td>
			
			</td>
			<td>
				<input type="submit" value="Подтвердить удаление">
			</td>
		</tr>
	</table>
	
	
</form>

{% endblock content %}

shop_project/main_app/templates/detailview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ object.product_name }}<br>
{{ product.product_countriesoforigin }} <br>
{{ category }}
</body>
</html>

shop_project/main_app/templates/form_create_product.html
{% extends 'supermain1.html' %}

{% load static %}
{% block button %}{% endblock %}
{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
		<tr>
			<td>
			<input type="submit" value="Создать товар">
			</td>
		</tr>
	</table>
	
	
</form>

{% endblock content %}

shop_project/main_app/templates/listview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Page listview</h1>
{{ products }}<br>
{{ object_list }}
</body>
</html>

shop_project/main_app/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Store</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>



{% if user.is_authenticated %}
<p>Welcome, {{ user.username }}</p>
<a href="{% url 'accounts:logout' %}">
    <button>Выйти</button>
</a>
{% else %}
<a href="{% url 'accounts:registration' %}">
    <button>Зарегистрироваться</button>
</a>
<a href="{% url 'accounts:login' %}">
    <button>Войти</button>
</a>
{% endif %}
<div style="float: right;">
    <a href="{% url 'main_app:create_product' %}"><button>Добавить товар</button></a>
</div>


<h1 style="text-align: center;">Welcome to our store</h1>
<h3 style="text-align: center; font-color: red;">{{ message }}</h3>
<div id="filter">
    <form action="" method="GET">
    <table>
        <tr>
            <td>
                {{ form.product_name.label }}
                {{ form.product_name }}
            </td>
            <td>
                {{ form.category_name.label }}
                {{ form.category_name }}
            </td>
            <td>
                {{ form.product_price.label }}
                {{ form.product_price }}
            </td>
            <td>
                {{ form.gl.label }}
                {{ form.gl }}
            </td>
            <td>
                <input type="submit" value="Найти">
            </td>
        </tr>
    </table>
</form>
</div>
<div>
    {% for product in products %}
    <div class="product_card">
        <div>
            {% for category in product.product_categories.all %} {{ category }} {% endfor %}
        </div>
        <div>
        {{ product.product_name }} {{ product.product_price }} руб.
        </div>
    </div>
    {% endfor %}
</div>

</body>
</html>

shop_project/main_app/templates/product_detail.html
{% extends 'supermain1.html' %}

{% load static %}

{% block button %}
{% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'main_app:update_product' product.id %}"><button>Изменить данные продукта</button></a>
          <a class="nav-link" href="{% url 'main_app:delete_product' product.id %}"><button>Удалить продукт</button></a>
{% endif %}
{% endblock button %}

{% block content %}
<div class="coupon">
  <div class="container">
    <h3>{{ product.product_name }}</h3>
  </div>
  <img src="{{ product.product_image.url }}" alt="Avatar" style="width: 30%;">
  <div class="container" style="background-color:white">
    <h2><b>{{ product.product_price }} руб.</b></h2>
    <p>Описание: {{ product.product_description }}</p>
  </div>
  <div class="container">
    <p>Наличие на складе:
	    <span class="promo">{% if product.is_available %}В наличии {{ product.product_quantity }} {{ product.product_units }} {% else %}Нет в
		    наличии{% endif %}</span></p>
    <p class="expire">Категория: {% for category in product.product_categories.all %}{{ category.category_name }}{% endfor %}</p>
  </div>
</div>

{% endblock content %}

shop_project/main_app/templates/supermain.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/supermain.css' %}">
    <title>Title</title>
</head>
<body>
<div class="navbar">
  <a href="#home">Home</a>
  <a href="#news">News</a>
  <a href="#contact">Contact</a>
</div>
<!-- The sidebar -->

<!--<div class="sidebar">-->
<!--  {% for category in categories %}-->
<!--  <a href="#about">{{ category.category_name }}</a>-->
<!--    {% endfor %}-->
<!--</div>-->

<!-- Page content -->
<div class="row">
    {% for product in object_list %}
  <div class="col-sm-6">
     <div class="card">
      <div class="card-body">
        <img src="{{ product.product_image.url }}" alt="Denim Jeans" style="width:100%">
        <h5 class="card-title">{{ product.product_name }}</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
  </div>
      {% endfor %}
</div>
<!--<div class="content">-->
<!--    {% for product in object_list %}-->
<!--    <div class="card">-->
<!--      <img src="{{ product.product_image.url }}" alt="Denim Jeans" style="width:100%">-->
<!--      <h1>{{ product.product_name }}</h1>-->
<!--      <p class="price">{{ product.product_price }}</p>-->
<!--      <p>Some text about the jeans..</p>-->
<!--      <p><button>Add to Cart</button></p>-->
<!--    </div>-->
<!--    {% endfor %}-->
<!--    <div class="paginator">-->
<!--            {% if page_obj.has_previous %}-->
<!--            <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>-->
<!--            &nbsp; &nbsp; | &nbsp; &nbsp;-->
<!--            {% endif %}-->
<!--            Часть №{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}-->
<!--            {% if page_obj.has_next %}-->
<!--            &nbsp;&nbsp;|&nbsp;&nbsp;-->
<!--            <a href="?page={{ page_obj.next_page_number }}">&gt;</a>-->
<!--            {% endif %}-->
<!--        </div>-->
<!--</div>-->
<footer>

</footer>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</html>

shop_project/main_app/templates/supermain1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/supermain1.css' %}">
    <title>Title</title>
</head>
<body>
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand btn-lg" href="#">Navbar</a>
    <button class="navbar-toggler btn-lg" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'main_app:supermain' %}">Главная</a>
        </li>
	      {% if user.is_authenticated %}
	      <li class="nav-item">
          <a class="nav-link" href="{% url 'main_app:product_form' %}">Создать продукт</a>
        </li>
	      {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
	      {% if user.is_authenticated %}
	      <form action="{% url 'accounts:logout' %}" method="GET">
		      <input type="hidden" name="url_logout" value="{{ request.path }}">
	          <input class="nav-link" type="submit" value="Выйти"><br>
	      </form>
	      {% else %}
	      <form action="{% url 'accounts:login' %}" method="GET">
		      <input type="hidden" name="next" value="{{ request.path }}">
	          <input type="submit" value="Войти"><br>
	      </form>
	      {% endif %}
      </ul>
	    {% block button %} {% endblock button %}
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>


<!-- The sidebar -->
<div class="sidebar">
    {% for category in categories %}
  <a href="{% url 'main_app:supermain1' category.id %}">{{ category.category_name }}</a>
    {% endfor %}
</div>



<!-- Page content -->

<div class="content">
	{% block content %}
    <div class="card-group card mb-3" style="row row-cols-1 row-cols-md-3 g-4">
    {% for product in object_list %}
        <div class="col-2">
             <div class="card h-100">
	             <a href="{% url 'main_app:productdetail' product.pk %}"><img src="{{ product.product_image.url }}"
	                                                               class="card-img-top" style="width:276px;"
	                                                       alt="..."></a>
                  <div class="card-body">
                    <h5 class="card-title">{{ product.product_name }}</h5>
                    <p class="card-text">{{ product.product_price }}</p>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
             </div>
        </div>
    {% endfor %}
    </div>
	{% endblock content %}
</div>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</html>

shop_project/main_app/templates/templateview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>
    {{ message }}
</h1>
<h2>
    {{ key }}
</h2>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Go back">
</form>
</body>
</html>

shop_project/main_app/templates/update_product.html
{% extends 'supermain1.html' %}

{% load static %}

{% block content %}
 <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table">
        {% for field in form %}
            <tr class="product_tr">
                <td class="product_td">
                    {{ field.label }}
                </td>
                <td class="product_td">
                    {{ field }}
                </td>
            </tr>
        {% endfor %}
            <tr class="product_tr">
                <td class="product_td">
                </td>
                <td class="product_td">
                    <input type="submit" value="Изменить">
                </td>
            </tr>
        </table>
    </form>
{% endblock content %}

shop_project/main_app/templates/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ message }}</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Go!">
</form>
{{ products }}
</body>
</html>